version: '3.7'

services:

  redis:
    image: redis:6.2 # eqalpha/keydb:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8084:80"
  
  node1:
    build:
      dockerfile: Dockerfile.varnish
      context: varnish
    restart: unless-stopped
    environment:
      BACKEND: "nginx"
    ports:
      - 8085:80

  purger_1:
    depends_on:
      - redis
      - node1
    build: 
      context: .
    restart: unless-stopped
    environment:
      PURGERY_ID: purgery_1
      REDIS_URL: redis://redis
      VARNISH_ADDR: node1:80

  node2:
    build:
      dockerfile: Dockerfile.varnish
      context: varnish
    restart: unless-stopped
    ports:
      - 8086:80

  purger_2:
    depends_on:
      - redis
      - node2
    build: 
      context: .
    restart: unless-stopped
    environment:
      PURGERY_ID: purgery_2
      REDIS_URL: redis://redis
      VARNISH_ADDR: node2:80
