version: '3.7'

services:

  redis:
    image: redis:6.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"

  node1:
    image: varnish:latest
    restart: unless-stopped
    ports:
      - 8085:80

  purger_1:
    depends_on:
      - redis
      - node1
    build: 
      context: .
    restart: unless-stopped
    environment:
      FLY_ALLOC_ID: purger_1
      REDIS_URL: redis://redis
      PURGE_ADDR: node1:80

  node2:
    image: varnish:latest
    restart: unless-stopped
    ports:
      - 8086:80

  purger_2:
    depends_on:
      - redis
      - node2
    build: 
      context: .
    restart: unless-stopped
    environment:
      FLY_ALLOC_ID: purger_2
      REDIS_URL: redis://redis
      PURGE_ADDR: node2:80
