name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        uses: docker://morphy/revive-action:v2
        with:
          config: "./revive.toml"
          path: "./..."

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        COVERPKG=$(go list ./... | tr '\n' ,)
        COVERPKG=${COVERPKG%?}
        go test -race -coverpkg=${COVERPKG} -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage report
      if: ${{ hashFiles('coverage.out') != '' }}
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
